baseURL = "http://example.org/"
languageCode = "en-us"
title = "Making with Code"
theme = "book"
publishdir = "../build"

[params]

  BookLogo = "fablearn.png"
  BookSection = "courses"
  CustomCSS = ["css/book_custom.css"]
  ExcludeTypesFromMenu = ["teaching", "notes"]

  ShowTeaching = true
  ShowNotes = true
